version: '3.3'

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-data:

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:7.5.7
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - monitoring