version: '3.3'

volumes:
  portainer-data:

networks:
  monitoring:
    driver: bridge

services:
  grafana:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8000:8000
      - 8443:9443
    networks:
      - monitoring